In [3]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.math.add(1,2)
print(x)

tf.Tensor(3, shape=(), dtype=int32)


In [3]:
x = tf.math.add([1,2],[3,4])
print(x)

tf.Tensor([4 6], shape=(2,), dtype=int32)


In [4]:
x = tf.math.square(2)
y = tf.math.square(3)
c = x + y
print(c)

tf.Tensor(13, shape=(), dtype=int32)


In [5]:
x = tf.math.reduce_sum([1,2,3])
print(x)

tf.Tensor(6, shape=(), dtype=int32)


In [6]:
x = tf.linalg.matmul([[1]],[[2,3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [9]:
x = np.ones([3,3])
t = tf.math.multiply(x,42)
print(t)

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [10]:
print(np.add(t,1))

[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


In [11]:
print(t.numpy())

[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [13]:
x = tf.random.uniform([3,3])
print("Is there any gpu available: ")
print(tf.config.list_physical_devices('GPU'))
print("Is the tensor on GPU : ")
print(x.device.endswith('GPU:0'))

Is there any gpu available: 
[]
Is the tensor on GPU : 
False


In [6]:
import time 
def time_matmul(x):
    start = time.time()
    for i in range(1,10):
        tf.linalg.matmul(x,x)
    
    result = time.time()- start
    print('10 loops : {:0.2f}ms' .format(1000*result))

print("On CPU : ")
with tf.device('CPU:0'):
    x = tf.random.uniform([1000,1000])
    assert x.device.endswith('CPU:0')
    time_matmul(x)
    

if tf.config.list_physical_devices('GPU'):
    print('On GPU : ')
    with tf.device('GPU:0'):
        x = tf.random.uniform([1000,1000])
        assert x.device.endswith('GPU:0')
        time_matmul(x)

On CPU : 
10 loops : 232.45ms
