In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
u = np.array(42);
print(u);

42


In [5]:
da = np.array([[1,2,3,4],[5,6,7,8]])
print(da)


[[1 2 3 4]
 [5 6 7 8]]


In [6]:
da3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(da3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(x.ndim)
print(da.ndim)
print(da3.ndim)

1
2
2


Indexing

In [8]:
x = np.array([1,2,3,4,5])
print(x[0])

1


In [10]:
y = np.array([[1,2,3],[4,5,6]])
print(y[0,1])

2


Slicing

In [11]:
x = np.array([1,2,3,4,5])
print(x[0:3])

[1 2 3]


In [13]:
print(x[-3:-1])

[3 4]


In [14]:
print(x[0:5:2])

[1 3 5]


In [15]:
y = np.array([[1,2,3],[4,5,6]])
print(y[0, 0:3])

[1 2 3]


DataTypes

In [20]:
x = np.array([1,2,3,4,5])
print(x.dtype)

int32


In [17]:
y = np.array(['apple','banana','orange'])
print(y.dtype)

<U6


In [19]:
b = np.array([1,0,1,0,1])
new_b = b.astype(bool)
print(new_b)

[ True False  True False  True]


Copy Vs View

In [21]:
x = np.array([1,2,3,4,5])
y = x.copy()
y[0] = 3
print(x)
print(y)

[1 2 3 4 5]
[3 2 3 4 5]


In [22]:
x = np.array([1,2,3,4,5])
y = x.view()
y[0] = 3
print(x)
print(y)

[3 2 3 4 5]
[3 2 3 4 5]


In [23]:
arr = np.array([1,2,3,4,5])
x= arr.copy();
y= arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


Shape

In [28]:
y = np.array([[1,2,3,4],[5,6,7,3]])
print(y.shape)

(2, 4)


ReShape

In [31]:
x = np.array([1,2,3,4,5,6,7,8])
y = x.reshape(2,4)
z= x.reshape(2,4,1)
print(x)
print(y)
print(z)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]


Iterating 

In [32]:
x = np.array([1,2,3,4,5])
for i in x:
    print(i)

1
2
3
4
5


In [34]:
y = np.array([[1,2,3,4],[5,6,7,8]])
for i in y:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [35]:
for i in y:
    for z in i:
        print(z)

1
2
3
4
5
6
7
8


In [36]:
z = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(z):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [37]:
s = np.array([1,2,4,5,6,3,4,2,5,6,2,4,5,2,])
for ind,i in np.ndenumerate(s):
    print(ind,i)

(0,) 1
(1,) 2
(2,) 4
(3,) 5
(4,) 6
(5,) 3
(6,) 4
(7,) 2
(8,) 5
(9,) 6
(10,) 2
(11,) 4
(12,) 5
(13,) 2


Joining Array

In [39]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
z = np.concatenate((x,y))
print(z)

[1 2 3 4 5 6 7 8]


In [46]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
z = np.concatenate((x,y), axis=0)
arr = np.stack((x,y),axis=1)
print(arr)
print(z)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [51]:
arr2 = np.hstack((x,y))
arr3 = np.vstack((x,y))
arr4 = np.dstack((x,y))
print(arr2)
print(arr3)
print(arr4)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


Split

In [55]:
x = np.array([1,2,3,4,5,6])
y = np.array_split(x,3)
print(y)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [57]:
print(y[0])
print(y[1])
print(y[2])

[1 2]
[3 4]
[5 6]


Searching

In [60]:
x = np.array([1,2,3,4,5])
print(np.where(x==7))

(array([], dtype=int64),)


In [61]:
print(np.where(x%2==0))

(array([1, 3], dtype=int64),)
