In [1]:
import numpy as np

In [2]:
x = [1,2,3,4,5]
y = [6,7,8,9,10]
z = np.add(x,y)
print(z)

[ 7  9 11 13 15]


In [3]:
x = np.array([1,2,3])
y = np.array([2,5,6])
z = np.add(x,y)
print(z)

[3 7 9]


Creating Own Function

In [4]:
def addTwo(x,y):
    return x + y;

addTwo = np.frompyfunc(addTwo,2,1)
print(addTwo([1,2,3,4,5],[6,7,8,9,10]))


[7 9 11 13 15]


In [6]:
print(type(addTwo))

<class 'numpy.ufunc'>


In [7]:
print(np.ufunc)

<class 'numpy.ufunc'>


In [9]:
x = np.array([1,2,3,4])
y=np.array([5,6,7,8])
a = np.add(x,y)
b= np.subtract(x,y)
c = np.multiply(x,y)
d = np.divide(x,y)
e = np.power(x,y)
f = np.mod(x,y)
print(a,b,c,d,e)
print(f)

[ 6  8 10 12] [-4 -4 -4 -4] [ 5 12 21 32] [0.2        0.33333333 0.42857143 0.5       ] [    1    64  2187 65536]
[1 2 3 4]
