In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7])
np.sum(arr)

28

In [3]:
np.mean(arr)

4.0

In [4]:
np.max(arr)

7

In [6]:
np.min(arr)

1

In [8]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])
arr_2d[0,1]

2

In [9]:
arr_2d[0]

array([1, 2, 3, 4])

In [10]:
arr_2d[:, :2]

array([[1, 2],
       [5, 6]])

In [14]:
mask = arr > 2

In [15]:
arr[mask]

array([3, 4, 5, 6, 7])

In [16]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
result = np.dot(matrix_a, matrix_b)

In [17]:
result

array([[19, 22],
       [43, 50]])

In [18]:
rand_ints = np.random.randint(1, 10, size=(2, 3))

In [19]:
rand_ints

array([[3, 9, 9],
       [2, 5, 3]])

In [21]:
def square(x):
    return x ** 2

vectorized_func = np.vectorize(square)
result = vectorized_func(arr)