In [1]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [11]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [12]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.rand(2,2)

array([[0.5336561 , 0.90095985],
       [0.35081357, 0.88490989]])

In [14]:
arr = np.array([1,2,3,4])

In [16]:
arr.shape

(4,)

In [17]:
arr.ndim

1

In [18]:
arr.size

4

In [19]:
arr.dtype

dtype('int64')

In [20]:
arr[1:3]

array([2, 3])

In [21]:
arr1[0,1]

2

In [22]:
arr1[:,2]

array([3, 6])

In [23]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = a + b
c

array([ 6,  8, 10, 12])

In [24]:
a -2

array([-1,  0,  1,  2])

In [25]:
a.sum()

10

In [26]:
a.mean()

2.5

In [27]:
a.max()

4

In [28]:
a.min()

1

In [38]:
ar = np.arange(6)

In [39]:
ar.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
arr3 = np.array([[1,2],[3,4]])
arr3.flatten()

array([1, 2, 3, 4])

In [42]:
arr3.T

array([[1, 3],
       [2, 4]])

In [44]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
np.dot(a,b)

70

In [46]:
x = np.array([[1,2],[3,4]])
eigenValues, eigenVector = np.linalg.eig(x)

In [47]:
eigenValues

array([-0.37228132,  5.37228132])

In [48]:
eigenVector

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [49]:
np.random.randint(0,10,(2,3))

array([[5, 5, 8],
       [8, 4, 2]])

In [50]:
arr[arr>3]

array([4])