In [1]:
import numpy as np

In [3]:
np.random.seed(42)
data = np.random.rand(6,3)
print("Original data" , data)

Original data [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]


In [9]:
mean = np.mean(data, axis=0)
std_dev = np.std(data, axis=0)
standardized_data = (data - mean) / std_dev
print("Standardized data" , standardized_data)

Standardized data [[-0.30416695  1.48951296  0.70770592]
 [ 0.50104489 -0.73396482 -1.28666066]
 [-1.44113101  1.25298377  0.25454476]
 [ 0.89414754 -1.11289581  1.53147678]
 [ 1.34098396 -0.57638586 -1.19722414]
 [-0.99087844 -0.31925023 -0.00984266]]


In [5]:
cov_matrix = np.cov(standardize_data, rowvar=False)
print("Covariance matrix" , cov_matrix)

Covariance matrix [[ 1.2        -0.81564056 -0.29062143]
 [-0.81564056  1.2         0.2612545 ]
 [-0.29062143  0.2612545   1.2       ]]


In [6]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)


Eigenvalues:
 [2.17230118 0.38376296 1.04393586]

Eigenvectors:
 [[-0.65925656  0.71165357  0.24275499]
 [ 0.65313745  0.70194359 -0.28405397]
 [ 0.37254833  0.02871207  0.92756852]]


In [7]:
k = 2  # Reduce to 2 dimensions
top_eigenvectors = eigenvectors[:, :k]
print("\nTop Eigenvectors:\n", top_eigenvectors)


Top Eigenvectors:
 [[-0.65925656  0.71165357]
 [ 0.65313745  0.70194359]
 [ 0.37254833  0.02871207]]


In [10]:
reduced_data = np.dot(standardized_data, top_eigenvectors)
print("\nReduced Data:\n", reduced_data)


Reduced Data:
 [[ 1.43703542  0.84941228]
 [-1.28904033 -0.19557421]
 [ 1.86327592 -0.1387536 ]
 [-0.74579745 -0.10089492]
 [-1.70653552  0.51535088]
 [ 0.44106196 -0.92954044]]
