In [2]:
import numpy as np

In [13]:
myArr = np.array([1,2,3,4,5])
myArr

array([1, 2, 3, 4, 5])

In [5]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_2d


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr_3d = np.array([[[1,2],[3,4],[5,6]]])
arr_3d

[[[1, 2], [3, 4], [5, 6]]]

In [7]:
arr_2d.shape

(2, 5)

In [ ]:
#Number of dimensions
arr_2d.ndim

2

In [10]:
arr_2d.size

10

In [11]:
myArr.dtype

dtype('int64')

In [14]:
myArr + 10

array([11, 12, 13, 14, 15])

In [15]:
myArr * 2

array([ 2,  4,  6,  8, 10])

In [16]:
newArr = np.array([5,6,7,8,9])
myArr + newArr

array([ 6,  8, 10, 12, 14])